import { Montserrat } from 'next/font/google'
import Style from './CSS/global.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
const bodyFont = Montserrat({
   subsets: ['latin'],
   weight: ['300', '800', '700']
   })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bodyFont.className}>
        <div className="container">
        <Navbar />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  )
}
